version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.22
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  logstash:
    image: logstash:7.17.22
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.17.22
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200