name: Running test before push
on:
  push:
    branches:
      - trunk
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Set up JDK 17
        uses: actions/setup-java
        with:
          java-version: 17
      - name: Run gradle
        run: gradle build
      - name: Run Test
        run: gradle test

